# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_email_confirms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='email_confirms',
            new_name='email_confirmed',
        ),
    ]
