# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171229_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
