# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20171229_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_head',
        ),
        migrations.AddField(
            model_name='school',
            name='email_website',
            field=models.URLField(default='https://dcmail.dubaicollege.org'),
            preserve_default=False,
        ),
    ]
