# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20171229_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
