# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_set_yeargroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='students',
        ),
        migrations.AlterField(
            model_name='set',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
