# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-31 16:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171231_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='students',
            field=models.ManyToManyField(related_name='set_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
