# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_set_year_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='students',
            field=models.ManyToManyField(related_name='set_students', to='users.Student'),
        ),
        migrations.AlterField(
            model_name='set',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
        ),
    ]
