# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180105_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='teacher',
        ),
    ]
