# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_set_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Teacher'),
            preserve_default=False,
        ),
    ]
