# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 08:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_set_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='students',
            field=models.ManyToManyField(related_name='set_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='set',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
