# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20180115_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
