# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180121_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
            preserve_default=False,
        ),
    ]
