# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-22 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_answer_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='additionalcomment',
            field=models.BooleanField(default=True),
        ),
    ]
