# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_form_additionalcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_created',
        ),
        migrations.AddField(
            model_name='answer',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
