# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-25 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180125_0826'),
        ('forms', '0008_auto_20180125_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='setID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Set'),
            preserve_default=False,
        ),
    ]
