# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-26 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0009_form_setid'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalcomment',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form_comment', to='forms.Form'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='additionalcomment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
