# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20180126_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
