# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_form_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
    ]
