# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0012_form_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='iteration',
            field=models.IntegerField(default=1),
        ),
    ]
