# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_form_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='form',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Form'),
        ),
    ]
