# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0015_remove_form_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
